---
title: "cmp CNV methods"
author: "bpf"
date: "10/4/2021"
output: html_document
keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/BioII/lulab_b/baopengfei/projects/exOmics/DNA-seq")

```


# read mat  
```{r}
#setwd("/BioII/lulab_b/baopengfei/projects/exOmics/DNA-seq")

## sample id
crc <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-CRC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
nc <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-NC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
stad <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-STAD-passQCloose.txt",header = F,stringsAsFactors = F)$V1


## define scale func (rm na value)
# stdize = function(x, ...) {2*(x - min(x, ...)) / (max(x, ...) - min(x, ...) - 1 )}  # (-1,1)
# stdize = function(x, ...) {(x - min(x, ...)) / (max(x, ...) - min(x, ...))}  # (0,1)
# stdize = function(x, ...) {(x - mean(x, ...)) / sd(x, ...) - mean(x, ...)}  # zscore, like scale(), u=0, sd=1
# x = rexp(100) 
# x[sample(1:100, size = 10)] <- NA 
# x = data.frame(x,x) 
# xo = apply(x,MARGIN = 2, FUN = stdize, na.rm = T)



## tpm
tpm <- read.csv("output/lulab/matrix/archive/TPM_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
rownames(tpm) <- unlist(lapply(strsplit(rownames(tpm),"\\|"), function(x) x[1]))

plot(x=tpm$`CRC-PKU-10-wgs`, y=tpm$`CRC-PKU-12-wgs`)
cor(tpm$`CRC-PKU-10-wgs`, tpm$`CRC-PKU-12-wgs`, method = "spearman",use = "complete.obs")

## cpm
tpm <- read.csv("output/lulab/matrix/archive/TMMcpm_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
rownames(cpm) <- unlist(lapply(strsplit(rownames(cpm),"\\|"), function(x) x[1]))

## tpm
gc.tpm <- read.csv("output/lulab/matrix/TPM_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
rownames(gc.tpm) <- unlist(lapply(strsplit(rownames(gc.tpm),"\\|"), function(x) x[1]))

## cpm
gc.cpm <- read.csv("output/lulab/matrix/TMMcpm_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
rownames(gc.cpm) <- unlist(lapply(strsplit(rownames(gc.cpm),"\\|"), function(x) x[1]))


## mask.depth
mask.depth <- read.csv("output/lulab/matrix/archive/CNVmaskDepthRatio_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
rownames(mask.depth) <- unlist(lapply(strsplit(rownames(mask.depth),"\\|"), function(x) x[1]))
mask.depth <- na.omit(mask.depth)

## gc.mask.depth
gc.mask.depth <- read.csv("output/lulab/matrix/CNVmaskDepthRatio_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
#gc.mask.depth[1:3,1:3]
mask.depth <- na.omit(mask.depth)

## wiseconderx
wiseconderx <- read.csv("output/lulab/matrix/CNVzscore_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
wiseconderx <- na.omit(wiseconderx)
table(is.na(wiseconderx))

## cnvkit
cnvkit <- read.csv("output/lulab/matrix/CNVkitlog2depth_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
cnvkit <- na.omit(cnvkit)


## gistic2
gistic2 <- read.csv("output/lulab/matrix/CNVgistic2All_matrix_gene.txt",sep = "\t",check.names = F,header = TRUE, row.names = 1)
gistic2 <- na.omit(gistic2)




## filter and scale
#tpm; gc.tpm; cpm; gc.cpm; mask.depth; gc.mask.depth; wiseconderx; cnvkit; gistic2
g <- Reduce(intersect, list(rownames(tpm),rownames(gc.tpm),rownames(cpm),rownames(gc.cpm),rownames(mask.depth),rownames(gc.mask.depth),rownames(wiseconderx),rownames(cnvkit),rownames(gistic2)))

tpm <- tpm[g,c(crc,stad,nc)]
tpm <- log2(tpm+1)
tpm <- as.data.frame(scale(tpm))

cpm <- cpm[g,colnames(tpm)]
cpm <- log2(cpm+1)
cpm <- as.data.frame(scale(cpm))

gc.tpm <- gc.tpm[g,colnames(tpm)]
gc.tpm <- log2(gc.tpm+1)
gc.tpm <- as.data.frame(scale(gc.tpm))

gc.cpm <- gc.cpm[g,colnames(tpm)]
gc.cpm <- log2(gc.cpm+1)
gc.cpm <- as.data.frame(scale(gc.cpm))

mask.depth <- mask.depth[g,colnames(tpm)]
#mask.depth <- log2(mask.depth+1)
mask.depth <- as.data.frame(scale(mask.depth))

gc.mask.depth <- gc.mask.depth[g,]  # colnames(tpm) ?????
#gc.mask.depth <- log2(gc.mask.depth+1)
gc.mask.depth <- as.data.frame(scale(gc.mask.depth))

wiseconderx <- wiseconderx[g,colnames(tpm)]
#wiseconderx <- log2(wiseconderx+1)
wiseconderx <- as.data.frame(scale(wiseconderx,))

cnvkit <- cnvkit[g,colnames(tpm)]
#cnvkit <- log2(cnvkit+1)
cnvkit <- as.data.frame(scale(cnvkit))

gistic2 <- gistic2[g,colnames(tpm)]
#gistic2 <- log2(gistic2+1)
gistic2 <- as.data.frame(scale(gistic2))

```


# basic correlation plot (multi methods per sample)
# tpm; gc.tpm; cpm; gc.cpm; mask.depth; gc.mask.depth; wiseconderx; cnvkit; gistic2
```{r echo=FALSE, fig.width=7, fig.height=7, dev='svg'}
s <- "NC-PKU-10-wgs" # NC-PKU-9-wgs  NC-PKU-10-wgs  NC-PKU-mix30-wgs
#m <- data.frame(row.names = rownames(tpm),tpm=tpm[[s]],gc.tpm=gc.tpm[[s]],cpm=cpm[[s]],gc.cpm=gc.cpm[[s]],mask.depth=mask.depth[[s]],gc.mask.depth=gc.mask.depth[[s]],wiseconderx=wiseconderx[[s]],cnvkit=cnvkit[[s]],gistic2=gistic2[[s]])
m <- data.frame(row.names = rownames(tpm),tpm=tpm[[s]],mask.depth=mask.depth[[s]],wiseconderx=wiseconderx[[s]],cnvkit=cnvkit[[s]],gistic2=gistic2[[s]])
m[1:5,1:5]
p1 <- PerformanceAnalytics::chart.Correlation(m,method="spearman", histogram=TRUE, pch=19)
p2 <- PerformanceAnalytics::chart.Correlation(m,method="pearson", histogram=TRUE, pch=19)


#cor(x, y, method = c("pearson", "kendall", "spearman"))


# pdf("./output/lulab/cmp_cnv_pearson.pdf")
# PerformanceAnalytics::chart.Correlation(m,method="pearson", histogram=TRUE, pch=19)
# dev.off()
# 
# pdf("./output/lulab/cmp_cnv_spearman.pdf")
# PerformanceAnalytics::chart.Correlation(m,method="spearman", histogram=TRUE, pch=19)
# dev.off()
# #cowplot::save_plot("./output/lulab/cmp_cnv_pearson.pdf",p1,base_height = 20, base_width = 20)


```




# CNV:   samples cor plot of multi  methods
```{r echo=FALSE, fig.width=15, fig.height=6, dev='svg',}

# read example mat
cor.m <- "spearman"  # spearman, pearson
tpm <- read.csv(paste0("output/lulab/sample_cor/DNA_CNV/","tpm","_",cor.m,"_gene.txt"),sep = "\t",check.names = F,header = TRUE)  

# filter sample ids 
crc <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-CRC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
nc <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-NC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
stad <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-STAD-passQCloose.txt",header = F,stringsAsFactors = F)$V1
tpm <- tpm[tpm$from %in% c(crc,stad,nc) & tpm$to %in% c(crc,stad,nc),]

# get var
rownames(tpm) <- paste0(tpm$from,".",tpm$to)
tpm$from.group <- unlist(lapply(strsplit(tpm$from,"-"), function(x) x[1]))
tpm$to.group <- unlist(lapply(strsplit(tpm$to,"-"), function(x) x[1]))
#head(tpm)
#table(tpm$to.group)



m <- c("tpm",  "cpm",  "cpm.tmm", "cpm.tmm.log", "mask.depth",  "wiseconderx", "cnvkit", "gistic2")
mat <- list() 

for (i in m){
  #i <- "tpm"
  tmp <- read.csv(paste0("output/lulab/sample_cor/DNA_CNV/",i,"_",cor.m,"_gene.txt"),sep = "\t",check.names = F,header = TRUE)
  tmp <- tmp[tmp$from %in% c(crc,stad,nc) & tmp$to %in% c(crc,stad,nc),]
  rownames(tmp) <- paste0(tmp$from,".",tmp$to)
  tmp <- tmp[rownames(tpm),]
  mat[[i]] <- tmp$cor
  #names(mat)[i] <- i
 # mat
}

df <- do.call("cbind",mat)
df <- as.data.frame(df)
#table(is.na(df))
#head(df)
#nrow(df)==length(rownames(tpm))
rownames(df) <- rownames(tpm)
df$from.group <- tpm$from.group 
df$to.group <- tpm$to.group
df$groups <- paste0(df$from.group,"vs",df$to.group)

#str(df.m)
#table(df.m$methods)
df.m <- tidyr::gather(df,key = "methods", value = cor, 1:8)
df.m$methods <- factor(df.m$methods, levels = c("tpm",  "cpm",  "cpm.tmm", "cpm.tmm.log", "mask.depth",  "wiseconderx", "cnvkit", "gistic2"))
df.m$groups <- factor(df$groups, levels = c("NCvsNC", "CRCvsCRC", "STADvsSTAD", "NCvsCRC", "STADvsNC", "STADvsCRC"))

# plot
library(ggplot2)
b <- runif(nrow(df.m), -0.2, 0.2)
ggplot(df.m, aes(x = methods, y = cor, fill=groups))+ 
      labs(title = paste0("Sample ",cor.m," correlation"))+  
      geom_boxplot(position=position_dodge(0.5),width=0.5,size=0.4,
                   outlier.alpha = 1, outlier.size = 0)+
      geom_point(aes(x=as.numeric(methods)+b,y=cor),color="black", stroke=0.5,alpha=0.02) +
      #geom_violin(draw_quantiles = T) +
      geom_hline(yintercept = 0, color="grey50",linetype="dashed") + 
      ylim(c(-1,1)) +
      ggsci::scale_fill_nejm() +
      theme_bw() + 
      theme(plot.title = element_text(size = 18,color="black",hjust = 0.5,face="bold",family="arial"),
            axis.title = element_text(size = 18,color ="black",face="bold",family="arial"), 
            axis.text = element_text(size= 18,color = "black",family="arial"),
            panel.grid.minor.y = element_blank(),
            panel.grid.minor.x = element_blank(),
            axis.text.x = element_text(angle = 45, hjust = 1 ),
            panel.grid=element_blank(),
            legend.position = "top",
            legend.text = element_text(size= 12),
            legend.title= element_text(size= 12))

## basic stat
library(dplyr)
df.m %>% group_by(groups,methods) %>% summarise(mean=mean(cor),median=median(cor)) %>% group_by(methods) 

#median(df.m[df.m$groups=="NCvsNC" & df.m$methods=="tpm","cor"],na.rm = T)

```



# DNA-nucleosome:   samples cor plot of multi  methods
```{r echo=FALSE, fig.width=15, fig.height=6, dev='svg',}

# read example mat
cor.m <- "pearson"  # spearman, pearson
tpm <- read.csv(paste0("output/lulab/sample_cor/DNA_NOV/","exon.cpm","_",cor.m,"_gene.txt"),sep = "\t",check.names = F,header = TRUE)  

# filter sample ids 
crc <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-CRC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
nc <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-NC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
stad <- read.delim("../../multi-omics-explore/meta/lulab/paired-wgs-STAD-passQCloose.txt",header = F,stringsAsFactors = F)$V1
tpm <- tpm[tpm$from %in% c(crc,stad,nc) & tpm$to %in% c(crc,stad,nc),]

# get var
rownames(tpm) <- paste0(tpm$from,".",tpm$to)
tpm$from.group <- unlist(lapply(strsplit(tpm$from,"-"), function(x) x[1]))
tpm$to.group <- unlist(lapply(strsplit(tpm$to,"-"), function(x) x[1]))
#head(tpm)
#table(tpm$to.group)



m <- c("exon.cpm",  "exon.depth",  "mean.cpm",  "mean.depth",  "min.cpm",  "min.depth")
mat <- list() 

for (i in m){
  #i <- "tpm"
  tmp <- read.csv(paste0("output/lulab/sample_cor/DNA_NOV/",i,"_",cor.m,"_gene.txt"),sep = "\t",check.names = F,header = TRUE)
  tmp <- tmp[tmp$from %in% c(crc,stad,nc) & tmp$to %in% c(crc,stad,nc),]
  rownames(tmp) <- paste0(tmp$from,".",tmp$to)
  tmp <- tmp[rownames(tpm),]
  mat[[i]] <- tmp$cor
  #names(mat)[i] <- i
 # mat
}

df <- do.call("cbind",mat)
df <- as.data.frame(df)
#table(is.na(df))
#head(df)
#nrow(df)==length(rownames(tpm))
rownames(df) <- rownames(tpm)
df$from.group <- tpm$from.group 
df$to.group <- tpm$to.group
df$groups <- paste0(df$from.group,"vs",df$to.group)

#str(df.m)
#table(df.m$methods)
df.m <- tidyr::gather(df,key = "methods", value = cor, 1:length(m))
df.m$methods <- factor(df.m$methods, levels = c("exon.cpm",  "exon.depth",  "mean.cpm",  "mean.depth",  "min.cpm",  "min.depth"))
df.m$groups <- factor(df$groups, levels = c("NCvsNC", "CRCvsCRC", "STADvsSTAD", "NCvsCRC", "STADvsNC", "STADvsCRC"))
#str(df.m)
#table(is.na(df.m$cor))
df.m <- df.m[!is.na(df.m$cor),]
df.m$cor <- as.numeric(df.m$cor)

# plot
library(ggplot2)
b <- runif(nrow(df.m), -0.2, 0.2)
ggplot(df.m, aes(x = methods, y = cor, fill=groups))+ 
      labs(title = paste0("Sample ",cor.m," correlation"))+  
      geom_boxplot(position=position_dodge(0.5),width=0.5,size=0.4,
                   outlier.alpha = 1, outlier.size = 0)+
      geom_point(aes(x=as.numeric(methods)+b,y=cor),color="black", stroke=0.5,alpha=0.02) +
      #geom_violin(draw_quantiles = T) +
      geom_hline(yintercept = 0, color="grey50",linetype="dashed") + 
      ylim(c(-1,1)) +
      ggsci::scale_fill_nejm() +
      theme_bw() + 
      theme(plot.title = element_text(size = 18,color="black",hjust = 0.5,face="bold",family="arial"),
            axis.title = element_text(size = 18,color ="black",face="bold",family="arial"), 
            axis.text = element_text(size= 18,color = "black",family="arial"),
            panel.grid.minor.y = element_blank(),
            panel.grid.minor.x = element_blank(),
            axis.text.x = element_text(angle = 45, hjust = 1 ),
            panel.grid=element_blank(),
            legend.position = "top",
            legend.text = element_text(size= 12),
            legend.title= element_text(size= 12))

## basic stat
library(dplyr)
df.m %>% group_by(groups,methods) %>% summarise(mean=mean(cor),median=median(cor)) %>% group_by(methods) 

#median(df.m[df.m$groups=="NCvsNC" & df.m$methods=="tpm","cor"],na.rm = T)

```




# DNA-Met:   samples cor plot of multi methods
```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/BioII/lulab_b/baopengfei/projects/exOmics/DIP-seq")

```

```{r echo=FALSE, fig.width=15, fig.height=6, dev='svg',}
options(stringsAsFactors = F)
# read example mat
cor.m <- "pearson"  # spearman, pearson
tpm <- read.csv(paste0("output/lulab/sample_cor/DNA_ProMet/","cpm","_",cor.m,"_gene.txt"),sep = "\t",check.names = F,header = TRUE)  

# filter sample ids 
crc <- read.delim("../../multi-omics-explore/meta/lulab/paired-medip-CRC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
nc <- read.delim("../../multi-omics-explore/meta/lulab/paired-medip-NC-passQCloose.txt",header = F,stringsAsFactors = F)$V1
stad <- read.delim("../../multi-omics-explore/meta/lulab/paired-medip-STAD-passQCloose.txt",header = F,stringsAsFactors = F)$V1
tpm <- tpm[tpm$from %in% c(crc,stad,nc) & tpm$to %in% c(crc,stad,nc),]

# get var
rownames(tpm) <- paste0(tpm$from,".",tpm$to)

str(tpm)
tpm$from.group <- unlist(lapply(strsplit(tpm$from,"-"), function(x) x[1]))
tpm$to.group <- unlist(lapply(strsplit(tpm$to,"-"), function(x) x[1]))
#head(tpm)
#table(tpm$to.group)
?strsplit

getwd()

m <- c("cpm",  "gc.cpm",  "cpm.5k",  "cpm.1k",  "cpm.200b")
mat <- list() 

for (i in m){
  #i <- "tpm"
  tmp <- read.csv(paste0("output/lulab/sample_cor/DNA_ProMet/",i,"_",cor.m,"_gene.txt"),sep = "\t",check.names = F,header = TRUE)
  tmp <- tmp[tmp$from %in% c(crc,stad,nc) & tmp$to %in% c(crc,stad,nc),]
  rownames(tmp) <- paste0(tmp$from,".",tmp$to)
  tmp <- tmp[rownames(tpm),]
  mat[[i]] <- tmp$cor
  #names(mat)[i] <- i
 # mat
}

df <- do.call("cbind",mat)
df <- as.data.frame(df)
#table(is.na(df))
#head(df)
#nrow(df)==length(rownames(tpm))
rownames(df) <- rownames(tpm)
df$from.group <- tpm$from.group 
df$to.group <- tpm$to.group
df$groups <- paste0(df$from.group,"vs",df$to.group)

#str(df.m)
#table(df.m$methods)
df.m <- tidyr::gather(df,key = "methods", value = cor, 1:length(m))  # change !!!!
df.m$methods <- factor(df.m$methods, levels = m )

table(df.m$methods)

df.m$groups <- factor(df$groups, levels = c("NCvsNC", "CRCvsCRC", "STADvsSTAD", "NCvsCRC", "STADvsNC", "STADvsCRC"))
#str(df.m)
#table(is.na(df.m$cor))
df.m <- df.m[!is.na(df.m$cor),]
df.m$cor <- as.numeric(df.m$cor)

# plot
library(ggplot2)
b <- runif(nrow(df.m), -0.2, 0.2)
ggplot(df.m, aes(x = methods, y = cor, fill=groups))+ 
      labs(title = paste0("Sample ",cor.m," correlation"))+  
      geom_boxplot(position=position_dodge(0.5),width=0.5,size=0.4,
                   outlier.alpha = 1, outlier.size = 0)+
      geom_point(aes(x=as.numeric(methods)+b,y=cor),color="black", stroke=0.5,alpha=0.02) +
      #geom_violin(draw_quantiles = T) +
      geom_hline(yintercept = 0, color="grey50",linetype="dashed") + 
      ylim(c(-1,1)) +
      ggsci::scale_fill_nejm() +
      theme_bw() + 
      theme(plot.title = element_text(size = 18,color="black",hjust = 0.5,face="bold",family="arial"),
            axis.title = element_text(size = 18,color ="black",face="bold",family="arial"), 
            axis.text = element_text(size= 18,color = "black",family="arial"),
            panel.grid.minor.y = element_blank(),
            panel.grid.minor.x = element_blank(),
            axis.text.x = element_text(angle = 45, hjust = 1 ),
            panel.grid=element_blank(),
            legend.position = "top",
            legend.text = element_text(size= 12),
            legend.title= element_text(size= 12))

## basic stat
#library(dplyr)
#df.m %>% group_by(groups,methods) %>% summarise(mean=mean(cor),median=median(cor)) %>% group_by(methods) 


```

